
export const FETCH_LOGIN_DATA = 'FETCH_LOGIN_DATA'
export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS'
export const GET_DETAILS = 'GET_DETAILS'
export const GET_CONTACT = 'GET_CONTACT'
export const GET_USERNAME_FORGOT = 'GET_USERNAME_FORGOT'
export const LOG_OUT = 'LOG_OUT'
export const BRANCH_ID = 'BRANCH_ID'
export const SHOW_COACH_MARK = 'SHOW_COACH_MARK'
export const SHOW_COACH_MARK_SCV = 'SHOW_COACH_MARK_SCV'
export const SET_FCM_TOKEN = 'SET_FCM_TOKEN'
export const SET_FCM_NOTIFICATION = 'SET_FCM_NOTIFICATION'
export const SET_KEYCLOACK_TOKEN_DATA = 'SET_KEYCLOACK_TOKEN_DATA'

export const CLEAR_DASHBOARD_DATA = 'CLEAR_DASHBOARD_DATA'
export const CLEAR_ALL_DASHBOARD_DATA = 'CLEAR_ALL_DASHBOARD_DATA'

export const GET_FLEET_VEHICLE_DATA = 'GET_FLEET_VEHICLE_DATA'
export const GET_FLEET_WIDGET_DATA = 'GET_FLEET_WIDGET_DATA'
export const GET_LIVE_FLEET_VEHICLE_DATA = 'GET_FLEET_VEHICLE_DATA'
export const GET_FLEET_VEHICLE_LIST = 'GET_FLEET_VEHICLE_LIST'
export const GET_FLEET_TRIP_DATA = 'GET_FLEET_TRIP_DATA'
export const GET_FLEET_TRIP_VEHICLE_DATA = 'GET_FLEET_TRIP_VEHICLE_DATA'
export const RESET_FLEET_DATA = 'RESET_FLEET_DATA'

export const AVERAGE_TRIP_COST_DATA = 'AVERAGE_TRIP_COST_DATA'
export const AVERAGE_TRIP_COST_LIST = 'AVERAGE_TRIP_COST_LIST'

export const VEHICLE_UTILIZATION_DATA = 'VEHICLE_UTILIZATION_DATA'
export const FUEL_FILLED_DATA = 'FUEL_FILLED_DATA'

export const GET_DRIVER_ALERT_LIST = 'GET_DRIVER_ALERT_LIST'
export const CLEAR_ALERT_LIST = 'CLEAR_DRIVER_ALERT_LIST'
export const GET_TRIP_ALERT_LIST = 'GET_TRIP_ALERT_LIST'
export const GET_VEHICLE_ALERT_LIST = 'GET_VEHICLE_ALERT_LIST'
export const GET_FUEL_THEFT_ALERT_LIST = 'GET_FUEL_THEFT_ALERT_LIST'
export const SET_ALERT_COUNT = 'SET_ALERT_COUNT'
export const CLEAR_ALL_ALERTS = 'CLEAR_ALL_ALERTS'


export const GET_FLEET_OCCUPANCY_DATA = 'GET_FLEET_OCCUPANCY_DATA'
export const GET_FLEET_OCCUPANCY_DATA_UNASSIGNED = 'GET_FLEET_OCCUPANCY_DATA_UNASSIGNED'
export const GET_FLEET_DELAYED_COUNT = 'GET_FLEET_DELAYED_COUNT'

export const GET_VEHICLE_STATUS_COUNT = 'GET_VEHICLE_STATUS_COUNT'
export const GET_ASSIGNED_VEHICLES = 'GET_ASSIGNED_VEHICLES'
export const GET_UNASSIGNED_VEHICLES = 'GET_UNASSIGNED_VEHICLES'
export const GET_IN_SERVICE_VEHICLES = 'GET_IN_SERVICE_VEHICLES'

export const GET_BRANCH = 'GET_BRANCH'

export const GET_OVERALL_COST_DATA_FOR_TRIP = 'GET_OVERALL_COST_DATA_FOR_TRIP'
export const GET_COMPLETE_OVERALL_COST_DATA_FOR_TRIP = 'GET_COMPLETE_OVERALL_COST_DATA_FOR_TRIP'
export const GET_OVERALL_COST_DATA_FOR_VEHICLE = 'GET_OVERALL_COST_DATA_FOR_VEHICLE'
export const GET_COMPLETE_OVERALL_COST_DATA_FOR_VEHICLE = 'GET_COMPLETE_OVERALL_COST_DATA_FOR_VEHICLE'
export const GET_VEHICLE_OVERALL_COST_DATA = 'GET_VEHICLE_OVERALL_COST_DATA'
export const GET_PER_TON_OVERALL_COST_DATA = 'GET_PER_TON_OVERALL_COST_DATA'
export const GET_TRIP_OVERALL_COST_DATA = 'GET_TRIP_OVERALL_COST_DATA'

export const GET_OVERALL_COST_DATA_FOR_TYRE = 'GET_OVERALL_COST_DATA_FOR_TYRE'
export const GET_OVERALL_COST_DATA_FOR_OTHER = 'GET_OVERALL_COST_DATA_FOR_OTHER'
export const GET_TRIP_COST_SUMMATION = 'GET_TRIP_COST_SUMMATION'
export const GET_VEHICLE_COST_SUMMATION = 'GET_VEHICLE_COST_SUMMATION'

export const GET_INCIDENTS_DATA = 'GET_INCIDENTS_DATA'
export const GET_LIVE_INCIDENTS = 'GET_LIVE_INCIDENTS'
export const GET_LIVE_INCIDENTS_DATA = 'GET_LIVE_INCIDENTS_DATA'
export const GET_TOTAL_INCIDENTS = 'GET_TOTAL_INCIDENTS'

export const FETCH_DRIVER_DATA = 'FETCH_DRIVER_DATA'
export const FETCH_DRIVER_STATUS_COUNT = 'FETCH_DRIVER_STATUS_COUNT'
export const REMOVE_DRIVER_DATA = 'REMOVE_DRIVER_DATA'
export const CLEAR_ALL_DRIVER_DATA = 'CLEAR_ALL_DRIVER_DATA'

export const SET_DRIVER_SCORE_LEADERBOARD = 'SET_DRIVER_SCORE_LEADERBOARD'

export const SET_DRIVING_BEHAVIOUR_DATA = 'SET_DRIVING_BEHAVIOUR_DATA'

export const SELECTED_VEHICLE = 'SELECTED_VEHICLE'

//////////////

export const GET_VEHICLE_LAST_COORDS= 'GET_VEHICLE_LAST_COORDS'
export const GET_DISTANCE_TO_SERVICE = 'GET_DISTANCE_TO_SERVICE'

export const GET_TRIP = 'GET_TRIP';
export const GET_TRIP_DETAILS = 'GET_TRIP_DETAILS';
export const LIVE_TRIP_ID = 'LIVE_TRIP_ID';
export const GET_TRIP_DETAILS_BY_ID = 'GET_TRIP_DETAILS_BY_ID';
export const GET_LIVE_TRIP = 'GET_LIVE_TRIP';
export const EMPTY_LIVE_TRIP = 'EMPTY_LIVE_TRIP';
export const GET_ONGOING_TRIP = 'GET_ONGOING_TRIP';
export const EMPTY_ONGOING_TRIP = 'EMPTY_ONGOING_TRIP';
export const GET_PREVIOUS_TRIP = 'GET_PREVIOUS_TRIP';
// export const UNLOAD_PREVIOUS_TRIP = 'UNLOAD_PREVIOUS_TRIP';
export const GET_PAUSE_TRIP_STATUS = 'GET_PAUSE_TRIP_STATUS'
export const CLEAR_TRIP_DATA = 'CLEAR_TRIP_DATA'

export const GET_OTP = 'GET_OTP';
export const GET_TOKEN = 'GET_TOKEN';

export const GET_TRIP_STATUS = 'GET_TRIP_STATUS';

export const SET_LOAD_TIME = 'GET_LOAD_TIME'
export const SET_UNLOAD_TIME = 'GET_UNLOAD_TIME'

export const GET_VEHICLE_DETAILS = 'GET_VEHICLE_DETAILS'
export const EMPTY_VEHICLE_DETAILS = 'EMPTY_VEHICLE_DETAILS'

export const UNLOAD_PREVIOUS_TRIP = 'UNLOAD_PREVIOUS_TRIP'

///SCV NOTIFICATIOS
export const NAVIGATE_TO_NOTIFICATION = 'NAVIGATE_TO_NOTIFICATION';
export const EMPTY_NOTIFICATION = 'EMPTY_NOTIFICATION'
//Events - Reporting
export const REPORTING_EVENTS = 'REPORTING_EVENTS'
export const GET_DRIVING_BEHAVIOUR = 'GET_DRIVING_BEHAVIOUR'
export const SET_FUEL_CONSUMPTION = 'SET_FUEL_CONSUMPTION'
export const SET_VEHICLE_USAGE = 'SET_VEHICLE_USAGE'
export const CLEAR_ALL_REPORTING = 'CLEAR_ALL_REPORTING'

//State api
export const EGURU_STATE_API_TOKEN = 'EGURU_STATE_API_TOKEN'
export const GET_VEHICLE_MASTER_DETAILS = 'GET_VEHICLE_MASTER_DETAILS'
export const GET_VEHICLE_APPROVAL = 'GET_VEHICLE_APPROVAL'
export const GET_VEHICLE_COUNT = 'GET_VEHICLE_COUNT'
export const CLEAR_VEHICLE_MASTER_DETAILS = 'CLEAR_VEHICLE_MASTER_DETAILS'
export const EMPTY_VEHICLE_DATA = 'EMPTY_VEHICLE_DATA'


// ************************************* BANDHU APP *************************************

export const SET_USER_VISITED = 'SET_USER_VISITED';
export const SET_REGISTERED = 'SET_REGISTERED';
export const OTP_VERIFIED = 'OTP_VERIFIED';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT';
export const TOKEN_REFRESHED = 'TOKEN_REFRESHED';
export const BANDHU_USER_DETAILS = 'BANDHU_USER_DETAILS';
export const RESET_BANDHU_DATA = 'RESET_BANDHU_DATA'

// ************************************* BANDHU APP *************************************

// ************************************* TMSC APP *************************************

export const TMSC_LOGIN = 'TMSC_lOGIN'
export const TMSC_LOGOUT = 'TMSC_LOGOUT'

// ************************************* TMSC APP *************************************


// ************************************* Delight APP *************************************

export const DELIGHT_LOGIN = 'DELIGHT_LOGIN'
export const DELIGHT_LOGOUT = 'DELIGHT_LOGOUT'
export const SET_DELIGHT_MEMBER_TYPE = 'SET_DELIGHT_MEMBER_TYPE'
export const SET_DELIGHT_POINTS_ORDER_DATA = "SET_DELIGHT_POINTS_ORDER_DATA"

// ************************************* Delight APP *************************************
